version: '3.9'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # HTTP access (Neo4j browser)
      - "7687:7687"   # Bolt protocol (Python driver, etc.)
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_PLUGINS=["apoc", "bloom", "graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
    volumes:
      - ./data/data:/data
#      - ./data/neo4j/logs:/logs
      - ./data/import:/var/lib/neo4j/import
#       - ./neo4j/import:/import

  neodash:
    image: nielsdejong/neodash:latest
    platform: linux/amd64
    container_name: neodash
    ports:
      - "5005:5005"
    depends_on:
      - neo4j
